### PR TITLE
Math Magician: Component

### PR DESCRIPTION
**Pull request by manzitresor**
### Project requirements

- [ ] Delete all the boilerplate from Create React App
- [ ] Create a new directory called components
- [ ] Inside components, I created a new Calculator.js file.
- [ ] Inside components, I created a child component calScreen.js file.

### CODE REVIEW

**Review by Ibizugbe — CHANGES_REQUESTED** [review]
Hi @manzitresor 👋👋, 

tryagain


Good job so far!👍
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅✅

- [x] Linters are passing👍.
- [x] `components` directory has been created that contains a `Cakculator.js` file👍.
- [x] Functional components is used in `calculator.js` 👍.
- [x] Calculator matches the design👍.


## Required Changes ♻️

- [ ] Nice job taking away the boilerplate files from CRA😉. Let's also do well to take away the boilerplate styles in the `index.css` as we are also required to take the boilerplate styles too👍.
image

- [ ] Let's also ensure the `calculator.js` has atleast one child components😉. apart from this being a requirement, code splitting makes our code base easily maintainable and understandable. there are several ways your calculator component app can be split😉. You can make the `screen` one component and the `buttons` another components😉. 
image
 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by manzitresor** [comment]
Hi @Ibizugbe Thanks for Review feedback 🤝 
I will take into consideration required changes

**Review by Abenezer-Tilahun — APPROVED** [review]
Hi @manzitresor 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct Git-Flow.
✔️ Professional README  
✔️ Good Commit Messages
✔️ Good job for Implemented Suggested changes.

## Optional suggestions 
 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

**Comment by manzitresor** [comment]
Hi @Abenezer-Tilahun Thank you so much for approving my project 
it motivated me. 🥇 
cheers 🍾

**Pull request merged**
